CREATE TABLE Users(user_id VARCHAR(255) PRIMARY KEY NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT 'user')


SELECT * FROM Users