###REGISTER USER
POST http://localhost:5700/users/register
Content-Type: application/json

{
    "username": "Timo",
    "email": "John1@example.com",
    "password": "john"
}

###LOGIN USER
POST http://localhost:5700/users/login
Content-Type: application/json

{
    "email": "mary12@gmail.com",
    "password": "password1"
}

### FETCH SINGLE USER
GET http://localhost:5700/users/1edab374-b9a4-49c4-9c6a-b611b6817668
Content-Type: application/json


###SWITCH ROLES
PUT http://localhost:5700/users/switch-role
Content-Type: application/json

{
    "user_id":"58084774-3d48-4fa0-8df5-f64f6561d69f"
}


###CHANGE USER PASSWORD
PUT http://localhost:5700/users/mary12@gmail.com
Content-Type: application/json

{

    "password": "password1"
}