###REGISTER USER
POST http://localhost:5700/users/register
Content-Type: application/json

{
    "username": "marshal",
    "email": "marshal@example.com",
    "password": "marshal"
}

###LOGIN USER
POST http://localhost:5700/users/login
Content-Type: application/json

{
    "email": "John1@example.com",
    "password": "password7"
}



###FETCH ALL USERS
GET http://localhost:5700/users/fetch-all-users
Content-Type: application/json



### FETCH SINGLE USER
GET http://localhost:5700/users/a8d96a5e-1d87-4611-8245-bdc24b7a6bb5
Content-Type: application/json


###SWITCH ROLES
PUT http://localhost:5700/users/switch-role
Content-Type: application/json

{
    "user_id":"7fd5268b-8575-4259-ae94-ff70cec66fcf"
}


###CHANGE USER PASSWORD
PUT http://localhost:5700/users/john1@gmail.com
Content-Type: application/json

{
    "password": "12345678"
}


###DELETE USER
DELETE http://localhost:5700/users/delete/48bb7589-dcd6-49e8-a19b-8cd84634ebbe