###REGISTER USER
POST http://localhost:5700/users/register
Content-Type: application/json

{
    "username": "marshal",
    "email": "marshal@example.com",
    "password": "marshal"
}

###LOGIN USER
POST http://localhost:5700/users/login
Content-Type: application/json

{
    "email": "marshal@example.com",
    "password": "password"
}



###FETCH ALL USERS
GET http://localhost:5700/users/fetch-all-users
Content-Type: application/json



### FETCH SINGLE USER
GET http://localhost:5700/users/1edab374-b9a4-49c4-9c6a-b611b6817668
Content-Type: application/json


###SWITCH ROLES
PUT http://localhost:5700/users/switch-role
Content-Type: application/json

{
    "user_id":"58084774-3d48-4fa0-8df5-f64f6561d69f"
}


###CHANGE USER PASSWORD
PUT http://localhost:5700/users/marshal@example.com
Content-Type: application/json

{
    "password": "password"
}